### ISSUE TITLE
Broken TrailTrends project URLs

### ISSUE THREAD

**Issue by EmiliaH** [OutdoorRD/trails-viz#244]
Our new TrailTrends url is `https://trailtrends.outdoorrd.org/#/` and `https://trailtrends.outdoorrd.org/` routes to this new URL with the `#`.  Cool and good!

However, Amy brought to my attention that `https://trailtrends.outdoorrd.org/dashboard/WestCascades` results in a 404 error! [Ruh roh](https://www.youtube.com/watch?v=R3SaxRRfJ4E)! 

This is the case with our King County dashboard link (https://trailtrends.outdoorrd.org/dashboard/KingCo), and Sama/I suspect all other project dashboard URLs. You can easily fix this issue by adding the `#` to the URL. But this means that any partner with a project dashboard link (which is everyone) will see a 404 error.  Sama and I talked about this and think it's worth finding a solutions.

So my questions are: 
1. What are the solutions to this? 
2. Is there one ~~ring to rule~~ solution to fix them all? 
3. How challenging are each of the possible solutions? How much time might they take?

FYI @davidye007, @jblehr, @woodsp, @sgwinder

**Comment by davidye007** [comment]
Hey @EmiliaH thanks for bringing this critical problem to attention!!
Here one solution I thought of: 
We could migrate the app hosting from GitHub Pages over to DigitalOcean Droplet. The reason behind switching over to hash routing is because GitHub Pages is a static hosting service without server-side logic. If we choose to host the app on the Droplet instead, we can set up a dynamic server using nginx. This probably won't take long (within a week) to setup because the nginx file will be very similar to the nginx configuration used previously on the GCP.

**Comment by jblehr** [comment]
I'll note that there are at least two other issues with the "hash" routing/hosting on GH pages that might be worth considering alongside this:
1. https://github.com/OutdoorRD/trails-viz/issues/243
2. https://github.com/OutdoorRD/trails-viz/issues/241

If there are many new issues that have been created from hosting on GH pages, it might be worth switching back (to hosting on the droplet), as @davidye007 suggests, rather than implementing separate workarounds for several different issues.

**Comment by davidye007** [comment]
This issue is closed with pull-requests #245 and #246. The dashboard is now hosted on DigitalOcean droplet. The dashboard is accessible without hash routing [here](https://trailtrends.outdoorrd.org/).

Closes #244

**Comment by davidye007** [comment]
This issue is closed with pull-requests #245 and #246. The dashboard is now hosted on DigitalOcean droplet. The dashboard is accessible without hash routing [here](https://trailtrends.outdoorrd.org/).

Closes #244

**Comment by jblehr** [comment]
Nice work @davidye007!
